#!/usr/bin/env bash

set -Eeu -o pipefail

declare -ig TESTS=0

_eq() {
    local expect=$1 ; shift
    result=$(./rpn "$@")
    if [[ $result != $expect ]]; then
        echo "$*: expected $expect != result $result"
        exit 1
    fi

    (( ++TESTS ))
}

_eq 3.0000 1 2 +
_eq 15.0000 1 2 3 4 5 sum
_eq 7.0000 3 4 5 drop +
_eq 1.4142 2 sqrt
_eq 2.0000 2 sqrt 2 '^'
_eq 1.4142 2 0.5 '^'
_eq 0.7071 2 sqrt 1 swap /
_eq 0.7071 2 -0.5 '^'
_eq 1.0000 1 2 '<'
_eq 65536.0000 1 16 '<<'

echo "$TESTS passed"
